title: ankita.github.io
description: Deep Reinforcement Learning Researcher
logo: https://aj-30.github.io/ankita.github.io/assets/img/logo.jpg
remote_theme: pages-themes/minimal@v0.2.0
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
